 project:
   type: website

 website:
   title: "Alaska electric service areas dataset"
   navbar:
     left:
       - href: index.qmd
         text: Home
       - about.qmd

 format:
   html:
     theme: darkly
       #light: flatly
       #dark: darkly
     css: styles.css
     toc: true
     respect-user-color-scheme: true
 execute:
  eval: true
  echo: false
  message: false
  warning: false
  output: true
  include: true

 editor: visual